// <auto-generated />
namespace DemoEF6CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fullspecforcolumnss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fullspecforcolumnss));
        
        string IMigrationMetadata.Id
        {
            get { return "202011080926209_full spec for columnss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
